NAME: 'FCL_bsds_pascal'
# 'again_RCF_vgg16bn_Adam_bsds_woms_softmaxcls_lstmbu_resumePASCAL_800' #'RCF_vgg16_bn_savemodel'#'new_github_adam_lr1e-4_Aug_0.3_savemodel'
MODEL:
    backbone: 'vgg16_bn'   #  'vgg16'(HED only) or 'vgg16_bn'(HED and RCF) or 'resnet50'(HED only)
    mode: 'RCF' # 'HED' OR 'RCF' or 'BDCN'
    pretrained: True
    loss_balance_weight: True
    loss_weight_list: [1, 1, 1, 1, 1, 1, 1] ## change dsn6 weight from 1->2 09-01 add dsn7
    upsample_layer: 'deconv'  # 'deconv' or 'bilinear', 'github'
    interpolate_mode: 'bilinear'  # 'bilinear' or 'nearest' if upsample_layer=='bilinear'
    freeze_bn: True  # for batchnorm
    freeze_bn_affine: True   # for batchnorm
    init_mode: 'Gaussian'  # 'Gaussian' or 'xavier'

    loss_func_logits: True # Default: True->false 20200915
    loss_reduce: True  # Default: True
    first_pad: 21  # Default: 34
    
    side_dilation: False
    
    sigmoid_attention: False #True
    vgg_attention: False
    boundary_weighted_attention: False
    
    focal_loss: False

    msblock: True
    cbam: False
    LSTM: False
    LSTM_bu: True
    LSTM_version: 'v1'
    supervision: 'normal'  # normal
    
    ClsHead: True  #2020-08-24
    cls_mode: 'softmax'
    
    change_conv5_dsn5: True
    
TRAIN: 
    resume: False
    param_path: '/project/jhliu4/XWJ/HED/ckpt/standard_RCF/log/RCF_vgg16bn_Adam_pascalaug_softmaxcls_lstmbu_savemodel_Dec17_20-26-22/epoch_56.pth'
    # '/project/jhliu4/XWJ/HED/ckpt/standard_RCF/log/RCF_vgg16bn_Adam_pascalaug_softmaxcls_lstmbu_savemodel_Dec17_20-26-22/epoch_56.pth'
    freeze_pretrained_param: False
    re_init_fuseweight: False
 
    init_lr: 0.0001 #0.0001  # if resume 0.00001
    update_method: "Adam"  # 'Adam' or 'SGD', 'Adam-sgd', 'meteorshowers', 'github'
    change_sgd_epoch: 6   # only for 'adam-sgd'
    change_sgd_lr: 0.0001     # only for 'adam-sgd'
  
    fusion_train: False
    nepoch: 20
    lr_list: [10, 15]  # use 2020-08-27
    lr_cof: [1, 100, 0.01, 0.001]  ## [1, 100, 0.01, 0.001]
    #lr_cof: [1, 10, 10, 10]  ## [1, 100, 0.01, 0.001]
    gamma: 1.1

    fixed_input: False
    batchsize: 1
    num_workers: 4

    update_iter: 10   # update gradients every n iters
    disp_iter: 1000  # num of iter 1000
    save_iter: 1 # 1
    test_iter: 1 # 1  # num of epoch

    random_seed: 555  # -1 is none
SAVE:
    MAT:
        normalize: True # whether divide the max value
    board_freq: 1

DATA:
    #root: /mnt/lustre/wuchongruo/projects/my_hed_new/data/HED-BSDS 
    root: ../data #mean: [104.00699, 116.66877, 122.67892]
    mean: [122.67892, 116.66877, 104.00699]
    gt_mode: gt_part 
    yita: 0.3

    AUG: 
        Crop500: False
        Rotate: False  # False
        RandomGaussianBlur: False  # False
        AdjustGamma: False  # False
        ColorJitter: True
        brightness: 0.3
        contrast: 0.3
        saturation: 0.3
        hue: 0.1
        HFlip: True
        MS: True #False  # 20201217 False->True 
    
    train_list: bsd500_pascal_train_pair.lst 
    # bsd500_pascalx8_aug_train_pair.lst 
    # bsd500_pascal_train_pair.lst 
    # train_pair.lst debug.lst 
    # train_pair.lst
    # pascal_train_pair.txt
    test_list: test.lst





