NAME: 'RCF_LSTM_CLS_bsds_savemodel' 
MODEL:
    backbone: 'vgg16_bn'   #  'vgg16'(HED only) or 'vgg16_bn'(HED and RCF) or 'resnet50'(HED only)
    mode: 'RCF' # 'HED' OR 'RCF' or 'BDCN'
    pretrained: True
    loss_balance_weight: True
    loss_weight_list: [1, 1, 1, 1, 1, 1, 1]
    upsample_layer: 'deconv'  # 'deconv' or 'bilinear', 'github'
    interpolate_mode: 'bilinear'  # 'bilinear' or 'nearest' if upsample_layer=='bilinear'
    freeze_bn: True  # for batchnorm
    freeze_bn_affine: True   # for batchnorm
    init_mode: 'Gaussian'  # 'Gaussian' or 'xavier'

    loss_func_logits: True # Default: True
    loss_reduce: True  # Default: True
    first_pad: 21  # Default: 34
    
    side_dilation: False
    
    sigmoid_attention: False #True
    vgg_attention: False
    boundary_weighted_attention: False
    
    focal_loss: False

    msblock: True  # check False->True
    cbam: False
    LSTM: False  # if True, use dsn1->dsn5, top-down
    LSTM_bu: True  # if True, use dsn5->dsn1, bottom-up
    LSTM_version: 'v1'
    supervision: 'normal'
    
    ClsHead: True
    cls_mode: 'max'
    
    change_conv5_dsn5: True
    
TRAIN: 
    resume: True
    param_path: ../HED/ckpt/standard_RCF_LSTM/log/RCF_LSTM_bottomup_vgg16_bsds_savemodel_Sep29_21-55-33/epoch_9.pth
    
    init_lr: 0.0001 # 0.0001
    update_method: "Adam"  # 'Adam' or 'SGD', 'Adam-sgd'
    change_sgd_epoch: 6   # only for 'adam-sgd'
    change_sgd_lr: 0.0001     # only for 'adam-sgd'

    nepoch: 20  # change 20->25
    lr_list: [10, 15]
    lr_cof: [1, 100, 0.01, 0.001]
    gamma: 1.1

    fixed_input: False
    batchsize: 1
    num_workers: 4

    update_iter: 10   # update gradients every n iters
    disp_iter: 1000  # num of iter
    save_iter: 1  # change 1->3
    test_iter: 1  # num of epoch

    random_seed: 555  # -1 is none
    
    fusion_train: False
    
SAVE:
    MAT:
        normalize: True # whether divide the max value
    board_freq: 1    
    
DATA:
    root: ../data
    mean: [122.67892, 116.66877, 104.00699]
    gt_mode: gt_part 
    yita: 0.3

    AUG: 
        Crop500: False
        Rotate: False
        RandomGaussianBlur: False
        AdjustGamma: False
        ColorJitter: True
        brightness: 0.3
        contrast: 0.3
        saturation: 0.3
        hue: 0.1
        HFlip: True
        MS: False  # change False->True, because of not using MS, MS training is not work properly.
    
    train_list: train_pair.lst
    # train_pair.lst # use bsds to train and validate the performance
    # bsd500_pascal_train_pair.lst checked use bsds+pascal to train
    test_list: test.lst





